name: Run check
on: [pull_request, push]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Run check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Build
        run: make

      - name: Run shellcheck with reviewdog
        uses: reviewdog/action-shellcheck@v1.27.0
        with:
          path: build
          pattern: join
